
spring:
  mvc:
   static-path-pattern: /resources/**
  resources:
      static-locations: classpath:/webapp/static
  application:
    name: wedding
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdel: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionrunsMillis: 60000
    url: jdbc:mysql://119.23.216.117:3306/mywedding
    username: root
    password: a+b=C.321!@#$


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  context-path: /wedding
  ssl:
    key-store: classpath:server.jks
    key-store-password: qwer1234
    keyStoreType: JKS
  port: 443
